### ISSUE TITLE
Sass @import paths break completely (incorrect root, double extensions, phantom partials)

### ISSUE THREAD

**Issue by zakdances** [mobilexag/plugin-sass#43] opened 2016-03-23 21:04 UTC
This is my `jspm.browser.js`:

```
SystemJS.config({
  baseURL: "/",
  paths: {
    "github:*": "jspm_packages/github/*",
    "npm:*": "jspm_packages/npm/*",
    "app/": "src/"
  }
});
```

In my `src` directory, I have `index.html`, `index.scss`, `app.ts`, and some child directories for the rest of my project. I'm importing `index.scss` in my `app.ts` with the line `var cssImport = System.import('./index.scss!')`.

Everything seemed to work fine until I added an import to `index.scss`. To my surprise, I found that

    // index.scss
    
    @import './components/misc/myStylesheet.scss';

failed to load and produced the following console error:

`[Error] Failed to load resource: A server with the specified hostname could not be found. (http://components/misc/myStylesheet.scss.scss)`

In an attempt to investigate the incorrect domain and a duplicate extension, I tried 

    // index.scss
    
    @import './locahost:3000/components/misc/myStylesheet';

It now correctly finds and loads `myStylesheet.scss`, but throws this new error:

`[Error] Failed to load resource: A server with the specified hostname could not be found. (http://locahost:3000/components/misc/_myStylesheet.scss)`

And now, apparently, it's also trying to load a nonexistent partial `_myStylesheet.scss`.

I'm not sure what's causing this odd behavior. Am I doing something wrong here or is this a bug? Is this related to https://github.com/mobilexag/plugin-sass/pull/40?

**Comment by screendriver** [comment] 2016-03-24 06:59
1. you are using a `jspm.browser.js`. This is something new in jspm **beta**. It's not a final release so there could be bugs with plugins at the moment
1. you are using TypeScript. `jspm` and `SystemJS`. Please look at issue #25
1. you are writing SASS code in CSS files (like `index.css`). You have to write SASS code in `.scss` files
1. I believe you have an error in your `baseUrl`. Please look at my unit tests where you can see how to import SASS files correctly. A sample GitHub project would be nice where I can reproduce your issue.

**Comment by zakdances** [comment] 2016-03-24 13:09
1. Duly noted. I wasn't aware that was a beta feature.
2. I'm not sure why Babel vs. Typescript should make a difference considering SystemJS can use them both target to target the same format (ES6). It's even set that way in my `jspm.config.js`:

    ```
    SystemJS.config({
      transpiler: "plugin-typescript",
      packages: {
        "app": {
          "format": "esm", // ← module format set to ES6
          "main": "app.js",
          "meta": {
            "*.js": {
              "loader": "plugin-typescript"
            }
          }
        }
      }
    });
    ```


3. There is no `index.css` in my project. Only `index.scss`. The ".css" was a typo on my part. Sorry about that...I fixed it now.

4. I'll look at the unit test, then see if I can create a simple test case for this. Maybe it can be shared with plunkr?

**Comment by screendriver** [comment] 2016-03-24 16:03
> I'll look at the unit test, then see if I can create a simple test case for this. Maybe it can be shared with plunkr?

plunkr is ok, but a simple GitHub repo where I can easily do a `npm install && jspm install && npm run` would be much nicer :wink:

**Comment by divmgl** [comment] 2016-03-28 00:47
Having the same problem, exactly as described. I've got it working now but it's looking for `_file.scss` when a file is loaded.

**Comment by zakdances** [comment] 2016-03-28 20:35
I'm still gonna create a simple test case for this when I get a chance.

**Comment by zakdances** [comment] 2016-03-31 05:59
Sorry about the delay. Ironically, this bug causes an even more catastrophic failure in my simple test then my real app!

For this test (created with `JSPM 0.17.0-beta.12`), I try to Sass `@import` a few different paths. They all fail...in fact, just the first import seems to make `sass.worker.js` immediately (and silently!) crash the entire app.

To run [the test](https://github.com/zakdances/jspmSassPluginBug):

1. `git clone https://github.com/zakdances/jspmSassPluginBug.git`

2. `npm install`

3. `jspm install`

4.  `npm run dev`

(Check your browser's error console if no log messages are printed to the html)

**Comment by divmgl** [comment] 2016-03-31 06:01
Thanks for your efforts on this. I had to give up on this plugin due to the performance issues and the bugs. Would love to tackle this in the future.

**Comment by zakdances** [comment] 2016-03-31 06:15
I have a reasonably large app and this plugin runs well for me (except for the incorrect @import paths).  It even loads unminified Angular Material without signifigant issue.

It's only on smaller tests that it crashes spectacularly.

My guess is that the slower compile times for large apps forces `sass.worker.js` (which uses web workers) to work in a more serial/synchronous fashion, avoiding (possible) concurrency bugs.

**Comment by KevCJones** [comment] 2016-04-12 10:18
Hey Guys,

Saw this one and i've managed to see the issue and apply a fix which works in the 0.16.x and 0.17.x JSPM varieties of my spin off.. 

I might be on the wrong path, @zakdances i wasn't exactly sure if you needed the 'domain' or if that was a side test to try and resolve the sub-scss loading issue. This might require more testing..

@screendriver & co how i solved it - being explicit with the protocol and host in the URLBase - [commit here](https://github.com/KevCJones/plugin-scss/commit/6f9e4f216e326e9639dec9e5fe8e1c7ac3204ff8)

Should be pretty easy to test on your side... i wasn't 100% sure if this blocked fringe cases like trying to import from another domain. If i'm right, it should be ok... 

@zakdances i wouldn't jump over to my plugin unless you have an explicit use for managing the css outputted yourself - the only reason i maintain it is for angular2 right now, and some people are using it for server-side stuff. However you can probably glean what i changed from [this fork ](https://github.com/KevCJones/jspmSassPluginBug)if you're looking for a quick fix while the guys here investigate this as an avenue for solving it.

**Comment by zakdances** [comment] 2016-04-12 10:34
@KevCJones Thanks for taking a look!

I don't want the domain in my real projects. Now or ever. The domain requirement was part of the bug, which is what I was demonstrating in my test (the paths without the domain simply didn't work).

HOWEVER, since publishing my test, screendriver released `plugin-sass v0.4.0` and the domain bug appears to be solved. But the redundant requests bug and explicit filename bug remain.

**Comment by KevCJones** [comment] 2016-04-12 14:04
Ah egg on my face there :) ah well i now can see what you mean and how they fixed it, different approach but same result. 

Re: Redundant calls
Nested @imports for me have always been at underscore prefixed files (telling SCSS compilers to not compile these because they are shared  code, possibly included in multiple other files. So i've never tried to resolve one that wasn't.

Is this a plugin issue? I would debate that no, this is a side effect of trying to @import an non underscore scss file while doing compilation on the fly in the browser.

If you consider the normal workflow for SCSS compilation is offline (via CLI tools or similar), this two step @import resolving is just hidden from you. Typical SCSS compilers will first check if the @import was indeed an '_' underscore prefixed file before trying to resolve the explicit file as you wrote it.  
Doing this 'on the fly'  the SCSS library is still following SCSS loading checks, but you're now seeing the failed usual '_' attempt via an xhr request. 

I would say that for during development this is acceptable, because when you compile your bundle this won't be a problem. You could remove the problem by simply making your nested @import '_'.

**Comment by KevCJones** [comment] 2016-04-12 14:06
RE: explicit filename issue. Yeah i think that probably should be something that the plugin could factor in an remedy. I'll explore this and see if i can spot an easy fix.

**Comment by KevCJones** [comment] 2016-04-12 14:42
Reading [the sass guide](http://sass-lang.com/guide)

> When you import a file you don't need to include the file extension .scss. Sass is smart and will figure it out for you. 

Running checks in the plugin, its clear that sass.js doesn't want an extension because its taking the import and doing the parse itself. Perhaps it's arguable that we should be following the sass spec and not passing the extension in?

**Comment by zakdances** [comment] 2016-04-12 19:20
The sass spec doesn't disallow, or even discourage, using extensions. The inference is a completely optional feature, and the sass plugin should behave the same, in theory.

But, like you alluded to, it's tricky because (unlike regular sass) the plugin must use *requests* to find files.

So the 404 errors may need to say (as long as they're not there in production). However explicit filepaths (with extensions) should be supported.

**Comment by KevCJones** [comment] 2016-04-12 22:05
Sorry you are right, i shouldn't have said 'spec'. Should of said  'guide' as i meant to. I didn't give up yet. I've been looking into the sass.importer interception point, which is where we could maybe treat poorly formed @imports by the sass.js lib itself. 

I'll post again if i have any success.

**Comment by KevCJones** [comment] 2016-04-12 22:49
@zakdances one solution i can put forward feels like a hacky fix, but the issue here is living inside sass.js. 

`const partialPath = resolved.replace(/\/([^/]*)$/, '/_$1')
                                        .replace(/.scss.scss/,'.scss')
                                        .replace(/.sass.sass/,'.scss');`

to replace [this line](https://github.com/mobilexag/plugin-sass/blob/master/src/sass-inject.js#L37)

When sass.js is doing its @imports its not paying any attention to the extension, and as i alluded to, seems to be simply assuming 'you don't need to add them, we will do that'. We could create an issue there, asking them to test for explicit @import  extensions and not affix one if present?

What do you recon?

**Comment by KevCJones** [comment] 2016-04-12 22:57
Part of me feels like we're missing a setting when i play [in this](http://medialize.github.io/playground.sass.js/) and see non of the issues.

**Comment by KevCJones** [comment] 2016-04-13 16:20
@zakdances so in the end the issue lived in a local file (resolve-path), a face-palm moment. But glad its solved the need for that hack. PR in place. Lets see if it thats a wrap?

**Closed** 2016-04-14 18:57 UTC
